apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nextjs-app
  namespace: argocd
spec:
  project: default

  source:
    # Ganti dengan URL repo Next.js kamu (repo yang sama dengan source code)
    repoURL: https://github.com/USERNAME/nextjs-app.git
    targetRevision: main
    path: k8s   # folder berisi deployment.yaml & service.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true