CREATE TABLE IF NOT EXISTS whatsapp_targets (
    id VARCHAR(36) PRIMARY KEY,
    label VARCHAR(255) NOT NULL,
    phone_number VARCHAR(50) NOT NULL,
    jid VARCHAR(255) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
