ALTER TABLE devices ADD COLUMN IF NOT EXISTS snmp_enabled BOOLEAN DEFAULT false;
ALTER TABLE devices ADD COLUMN IF NOT EXISTS snmp_community VARCHAR(255) DEFAULT 'public';
ALTER TABLE devices ADD COLUMN IF NOT EXISTS snmp_port INTEGER DEFAULT 161;
ALTER TABLE devices ADD COLUMN IF NOT EXISTS snmp_if_index INTEGER DEFAULT NULL;
